# Generated by Django 3.1.4 on 2021-01-09 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='image',
        ),
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
    ]
