# Generated by Django 3.1.4 on 2021-01-17 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddm', '0003_course_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
