# Generated by Django 3.1.4 on 2021-01-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddm', '0006_answer_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='library',
            name='photo',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
