# Generated by Django 3.1.4 on 2021-01-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddm', '0007_auto_20210119_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='photo',
        ),
        migrations.AlterField(
            model_name='library',
            name='files',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
