# Generated by Django 3.1.4 on 2021-01-25 15:14

import ddm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddm', '0008_auto_20210119_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='files',
            field=models.FileField(upload_to=ddm.models.get_file_path),
        ),
    ]
