# Generated by Django 3.1.4 on 2021-01-28 15:36

import ddm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddm', '0010_auto_20210129_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=ddm.models.get_file_path),
        ),
    ]
